/*
 * Java bean class for entity table cctt_cr_product 
 * Created on 1 Dec 2016 ( Date ISO 2016-12-01 - Time 22:11:06 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package com.ge.pw.ibct.beans;

import java.io.Serializable;

import java.util.Date;

/**
 * Entity bean for table "cctt_cr_product"
 * 
 * @author Telosys Tools Generator
 *
 */
public class CcttCrProduct implements Serializable
{
    private static final long serialVersionUID = 1L;

    private Integer    productId    ; // Primary Key

    private String     productLine  ;
    private String     productSerialNum ;
    private String     productType  ;
    private String     lockedInd    ;
    private String     createdBy    ;
    private Date       createdDate  ;
    private String     lastUpdatedBy ;
    private Date       lastUpdatedDate ;
    private Integer    iadPdmGepsId ;
    private Integer    csmGepsId    ;
    private String     operatingStatus ;
    private Date       shipDate     ;
    private String     siteDuns     ;
    private Date       firstFireDate ;
    private Integer    regionCode   ;
    private Integer    regionalFsmGepsId ;
    private String     csaInd       ;
    private Integer    cpmGepsId    ;
    private Date       cod          ;
    private String     leasePoolContractInd ;
    private String     unitNum      ;
    private String     productOwner ;
    private String     lockedOrderId ;
    private String     extnlPackageRefNum ;
    private String     orapParticipantInd ;
    private Integer    drivenEquipCode ;
    private Integer    defaultOpHours ;
    private Integer    defaultOpHoursUomCode ;
    private Integer    defaultOpCycleCnt ;
    private String     remoteMonitoredInd ;
    private Date       lastInprocessDate ;
    private String     primaryFuelCode ;

    /**
     * Default constructor
     */
    public CcttCrProduct()
    {
        super();
    }
    
    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR THE PRIMARY KEY 
    //----------------------------------------------------------------------
    /**
     * Set the "productId" field value
     * This field is mapped on the database column "product_id" ( type "int4", NotNull : true ) 
     * @param productId
     */
	public void setProductId( Integer productId )
    {
        this.productId = productId ;
    }
    /**
     * Get the "productId" field value
     * This field is mapped on the database column "product_id" ( type "int4", NotNull : true ) 
     * @return the field value
     */
	public Integer getProductId()
    {
        return this.productId;
    }

    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR DATA FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : product_line ( varchar ) 
    /**
     * Set the "productLine" field value
     * This field is mapped on the database column "product_line" ( type "varchar", NotNull : false ) 
     * @param productLine
     */
    public void setProductLine( String productLine )
    {
        this.productLine = productLine;
    }
    /**
     * Get the "productLine" field value
     * This field is mapped on the database column "product_line" ( type "varchar", NotNull : false ) 
     * @return the field value
     */
    public String getProductLine()
    {
        return this.productLine;
    }

    //--- DATABASE MAPPING : product_serial_num ( varchar ) 
    /**
     * Set the "productSerialNum" field value
     * This field is mapped on the database column "product_serial_num" ( type "varchar", NotNull : true ) 
     * @param productSerialNum
     */
    public void setProductSerialNum( String productSerialNum )
    {
        this.productSerialNum = productSerialNum;
    }
    /**
     * Get the "productSerialNum" field value
     * This field is mapped on the database column "product_serial_num" ( type "varchar", NotNull : true ) 
     * @return the field value
     */
    public String getProductSerialNum()
    {
        return this.productSerialNum;
    }

    //--- DATABASE MAPPING : product_type ( varchar ) 
    /**
     * Set the "productType" field value
     * This field is mapped on the database column "product_type" ( type "varchar", NotNull : false ) 
     * @param productType
     */
    public void setProductType( String productType )
    {
        this.productType = productType;
    }
    /**
     * Get the "productType" field value
     * This field is mapped on the database column "product_type" ( type "varchar", NotNull : false ) 
     * @return the field value
     */
    public String getProductType()
    {
        return this.productType;
    }

    //--- DATABASE MAPPING : locked_ind ( bpchar ) 
    /**
     * Set the "lockedInd" field value
     * This field is mapped on the database column "locked_ind" ( type "bpchar", NotNull : true ) 
     * @param lockedInd
     */
    public void setLockedInd( String lockedInd )
    {
        this.lockedInd = lockedInd;
    }
    /**
     * Get the "lockedInd" field value
     * This field is mapped on the database column "locked_ind" ( type "bpchar", NotNull : true ) 
     * @return the field value
     */
    public String getLockedInd()
    {
        return this.lockedInd;
    }

    //--- DATABASE MAPPING : created_by ( varchar ) 
    /**
     * Set the "createdBy" field value
     * This field is mapped on the database column "created_by" ( type "varchar", NotNull : true ) 
     * @param createdBy
     */
    public void setCreatedBy( String createdBy )
    {
        this.createdBy = createdBy;
    }
    /**
     * Get the "createdBy" field value
     * This field is mapped on the database column "created_by" ( type "varchar", NotNull : true ) 
     * @return the field value
     */
    public String getCreatedBy()
    {
        return this.createdBy;
    }

    //--- DATABASE MAPPING : created_date ( timestamp ) 
    /**
     * Set the "createdDate" field value
     * This field is mapped on the database column "created_date" ( type "timestamp", NotNull : true ) 
     * @param createdDate
     */
    public void setCreatedDate( Date createdDate )
    {
        this.createdDate = createdDate;
    }
    /**
     * Get the "createdDate" field value
     * This field is mapped on the database column "created_date" ( type "timestamp", NotNull : true ) 
     * @return the field value
     */
    public Date getCreatedDate()
    {
        return this.createdDate;
    }

    //--- DATABASE MAPPING : last_updated_by ( varchar ) 
    /**
     * Set the "lastUpdatedBy" field value
     * This field is mapped on the database column "last_updated_by" ( type "varchar", NotNull : true ) 
     * @param lastUpdatedBy
     */
    public void setLastUpdatedBy( String lastUpdatedBy )
    {
        this.lastUpdatedBy = lastUpdatedBy;
    }
    /**
     * Get the "lastUpdatedBy" field value
     * This field is mapped on the database column "last_updated_by" ( type "varchar", NotNull : true ) 
     * @return the field value
     */
    public String getLastUpdatedBy()
    {
        return this.lastUpdatedBy;
    }

    //--- DATABASE MAPPING : last_updated_date ( timestamp ) 
    /**
     * Set the "lastUpdatedDate" field value
     * This field is mapped on the database column "last_updated_date" ( type "timestamp", NotNull : true ) 
     * @param lastUpdatedDate
     */
    public void setLastUpdatedDate( Date lastUpdatedDate )
    {
        this.lastUpdatedDate = lastUpdatedDate;
    }
    /**
     * Get the "lastUpdatedDate" field value
     * This field is mapped on the database column "last_updated_date" ( type "timestamp", NotNull : true ) 
     * @return the field value
     */
    public Date getLastUpdatedDate()
    {
        return this.lastUpdatedDate;
    }

    //--- DATABASE MAPPING : iad_pdm_geps_id ( int4 ) 
    /**
     * Set the "iadPdmGepsId" field value
     * This field is mapped on the database column "iad_pdm_geps_id" ( type "int4", NotNull : false ) 
     * @param iadPdmGepsId
     */
    public void setIadPdmGepsId( Integer iadPdmGepsId )
    {
        this.iadPdmGepsId = iadPdmGepsId;
    }
    /**
     * Get the "iadPdmGepsId" field value
     * This field is mapped on the database column "iad_pdm_geps_id" ( type "int4", NotNull : false ) 
     * @return the field value
     */
    public Integer getIadPdmGepsId()
    {
        return this.iadPdmGepsId;
    }

    //--- DATABASE MAPPING : csm_geps_id ( int4 ) 
    /**
     * Set the "csmGepsId" field value
     * This field is mapped on the database column "csm_geps_id" ( type "int4", NotNull : false ) 
     * @param csmGepsId
     */
    public void setCsmGepsId( Integer csmGepsId )
    {
        this.csmGepsId = csmGepsId;
    }
    /**
     * Get the "csmGepsId" field value
     * This field is mapped on the database column "csm_geps_id" ( type "int4", NotNull : false ) 
     * @return the field value
     */
    public Integer getCsmGepsId()
    {
        return this.csmGepsId;
    }

    //--- DATABASE MAPPING : operating_status ( varchar ) 
    /**
     * Set the "operatingStatus" field value
     * This field is mapped on the database column "operating_status" ( type "varchar", NotNull : true ) 
     * @param operatingStatus
     */
    public void setOperatingStatus( String operatingStatus )
    {
        this.operatingStatus = operatingStatus;
    }
    /**
     * Get the "operatingStatus" field value
     * This field is mapped on the database column "operating_status" ( type "varchar", NotNull : true ) 
     * @return the field value
     */
    public String getOperatingStatus()
    {
        return this.operatingStatus;
    }

    //--- DATABASE MAPPING : ship_date ( timestamp ) 
    /**
     * Set the "shipDate" field value
     * This field is mapped on the database column "ship_date" ( type "timestamp", NotNull : true ) 
     * @param shipDate
     */
    public void setShipDate( Date shipDate )
    {
        this.shipDate = shipDate;
    }
    /**
     * Get the "shipDate" field value
     * This field is mapped on the database column "ship_date" ( type "timestamp", NotNull : true ) 
     * @return the field value
     */
    public Date getShipDate()
    {
        return this.shipDate;
    }

    //--- DATABASE MAPPING : site_duns ( varchar ) 
    /**
     * Set the "siteDuns" field value
     * This field is mapped on the database column "site_duns" ( type "varchar", NotNull : false ) 
     * @param siteDuns
     */
    public void setSiteDuns( String siteDuns )
    {
        this.siteDuns = siteDuns;
    }
    /**
     * Get the "siteDuns" field value
     * This field is mapped on the database column "site_duns" ( type "varchar", NotNull : false ) 
     * @return the field value
     */
    public String getSiteDuns()
    {
        return this.siteDuns;
    }

    //--- DATABASE MAPPING : first_fire_date ( timestamp ) 
    /**
     * Set the "firstFireDate" field value
     * This field is mapped on the database column "first_fire_date" ( type "timestamp", NotNull : false ) 
     * @param firstFireDate
     */
    public void setFirstFireDate( Date firstFireDate )
    {
        this.firstFireDate = firstFireDate;
    }
    /**
     * Get the "firstFireDate" field value
     * This field is mapped on the database column "first_fire_date" ( type "timestamp", NotNull : false ) 
     * @return the field value
     */
    public Date getFirstFireDate()
    {
        return this.firstFireDate;
    }

    //--- DATABASE MAPPING : region_code ( int4 ) 
    /**
     * Set the "regionCode" field value
     * This field is mapped on the database column "region_code" ( type "int4", NotNull : false ) 
     * @param regionCode
     */
    public void setRegionCode( Integer regionCode )
    {
        this.regionCode = regionCode;
    }
    /**
     * Get the "regionCode" field value
     * This field is mapped on the database column "region_code" ( type "int4", NotNull : false ) 
     * @return the field value
     */
    public Integer getRegionCode()
    {
        return this.regionCode;
    }

    //--- DATABASE MAPPING : regional_fsm_geps_id ( int4 ) 
    /**
     * Set the "regionalFsmGepsId" field value
     * This field is mapped on the database column "regional_fsm_geps_id" ( type "int4", NotNull : false ) 
     * @param regionalFsmGepsId
     */
    public void setRegionalFsmGepsId( Integer regionalFsmGepsId )
    {
        this.regionalFsmGepsId = regionalFsmGepsId;
    }
    /**
     * Get the "regionalFsmGepsId" field value
     * This field is mapped on the database column "regional_fsm_geps_id" ( type "int4", NotNull : false ) 
     * @return the field value
     */
    public Integer getRegionalFsmGepsId()
    {
        return this.regionalFsmGepsId;
    }

    //--- DATABASE MAPPING : csa_ind ( bpchar ) 
    /**
     * Set the "csaInd" field value
     * This field is mapped on the database column "csa_ind" ( type "bpchar", NotNull : false ) 
     * @param csaInd
     */
    public void setCsaInd( String csaInd )
    {
        this.csaInd = csaInd;
    }
    /**
     * Get the "csaInd" field value
     * This field is mapped on the database column "csa_ind" ( type "bpchar", NotNull : false ) 
     * @return the field value
     */
    public String getCsaInd()
    {
        return this.csaInd;
    }

    //--- DATABASE MAPPING : cpm_geps_id ( int4 ) 
    /**
     * Set the "cpmGepsId" field value
     * This field is mapped on the database column "cpm_geps_id" ( type "int4", NotNull : false ) 
     * @param cpmGepsId
     */
    public void setCpmGepsId( Integer cpmGepsId )
    {
        this.cpmGepsId = cpmGepsId;
    }
    /**
     * Get the "cpmGepsId" field value
     * This field is mapped on the database column "cpm_geps_id" ( type "int4", NotNull : false ) 
     * @return the field value
     */
    public Integer getCpmGepsId()
    {
        return this.cpmGepsId;
    }

    //--- DATABASE MAPPING : cod ( timestamp ) 
    /**
     * Set the "cod" field value
     * This field is mapped on the database column "cod" ( type "timestamp", NotNull : false ) 
     * @param cod
     */
    public void setCod( Date cod )
    {
        this.cod = cod;
    }
    /**
     * Get the "cod" field value
     * This field is mapped on the database column "cod" ( type "timestamp", NotNull : false ) 
     * @return the field value
     */
    public Date getCod()
    {
        return this.cod;
    }

    //--- DATABASE MAPPING : lease_pool_contract_ind ( bpchar ) 
    /**
     * Set the "leasePoolContractInd" field value
     * This field is mapped on the database column "lease_pool_contract_ind" ( type "bpchar", NotNull : false ) 
     * @param leasePoolContractInd
     */
    public void setLeasePoolContractInd( String leasePoolContractInd )
    {
        this.leasePoolContractInd = leasePoolContractInd;
    }
    /**
     * Get the "leasePoolContractInd" field value
     * This field is mapped on the database column "lease_pool_contract_ind" ( type "bpchar", NotNull : false ) 
     * @return the field value
     */
    public String getLeasePoolContractInd()
    {
        return this.leasePoolContractInd;
    }

    //--- DATABASE MAPPING : unit_num ( varchar ) 
    /**
     * Set the "unitNum" field value
     * This field is mapped on the database column "unit_num" ( type "varchar", NotNull : false ) 
     * @param unitNum
     */
    public void setUnitNum( String unitNum )
    {
        this.unitNum = unitNum;
    }
    /**
     * Get the "unitNum" field value
     * This field is mapped on the database column "unit_num" ( type "varchar", NotNull : false ) 
     * @return the field value
     */
    public String getUnitNum()
    {
        return this.unitNum;
    }

    //--- DATABASE MAPPING : product_owner ( varchar ) 
    /**
     * Set the "productOwner" field value
     * This field is mapped on the database column "product_owner" ( type "varchar", NotNull : false ) 
     * @param productOwner
     */
    public void setProductOwner( String productOwner )
    {
        this.productOwner = productOwner;
    }
    /**
     * Get the "productOwner" field value
     * This field is mapped on the database column "product_owner" ( type "varchar", NotNull : false ) 
     * @return the field value
     */
    public String getProductOwner()
    {
        return this.productOwner;
    }

    //--- DATABASE MAPPING : locked_order_id ( varchar ) 
    /**
     * Set the "lockedOrderId" field value
     * This field is mapped on the database column "locked_order_id" ( type "varchar", NotNull : false ) 
     * @param lockedOrderId
     */
    public void setLockedOrderId( String lockedOrderId )
    {
        this.lockedOrderId = lockedOrderId;
    }
    /**
     * Get the "lockedOrderId" field value
     * This field is mapped on the database column "locked_order_id" ( type "varchar", NotNull : false ) 
     * @return the field value
     */
    public String getLockedOrderId()
    {
        return this.lockedOrderId;
    }

    //--- DATABASE MAPPING : extnl_package_ref_num ( varchar ) 
    /**
     * Set the "extnlPackageRefNum" field value
     * This field is mapped on the database column "extnl_package_ref_num" ( type "varchar", NotNull : false ) 
     * @param extnlPackageRefNum
     */
    public void setExtnlPackageRefNum( String extnlPackageRefNum )
    {
        this.extnlPackageRefNum = extnlPackageRefNum;
    }
    /**
     * Get the "extnlPackageRefNum" field value
     * This field is mapped on the database column "extnl_package_ref_num" ( type "varchar", NotNull : false ) 
     * @return the field value
     */
    public String getExtnlPackageRefNum()
    {
        return this.extnlPackageRefNum;
    }

    //--- DATABASE MAPPING : orap_participant_ind ( bpchar ) 
    /**
     * Set the "orapParticipantInd" field value
     * This field is mapped on the database column "orap_participant_ind" ( type "bpchar", NotNull : false ) 
     * @param orapParticipantInd
     */
    public void setOrapParticipantInd( String orapParticipantInd )
    {
        this.orapParticipantInd = orapParticipantInd;
    }
    /**
     * Get the "orapParticipantInd" field value
     * This field is mapped on the database column "orap_participant_ind" ( type "bpchar", NotNull : false ) 
     * @return the field value
     */
    public String getOrapParticipantInd()
    {
        return this.orapParticipantInd;
    }

    //--- DATABASE MAPPING : driven_equip_code ( int4 ) 
    /**
     * Set the "drivenEquipCode" field value
     * This field is mapped on the database column "driven_equip_code" ( type "int4", NotNull : false ) 
     * @param drivenEquipCode
     */
    public void setDrivenEquipCode( Integer drivenEquipCode )
    {
        this.drivenEquipCode = drivenEquipCode;
    }
    /**
     * Get the "drivenEquipCode" field value
     * This field is mapped on the database column "driven_equip_code" ( type "int4", NotNull : false ) 
     * @return the field value
     */
    public Integer getDrivenEquipCode()
    {
        return this.drivenEquipCode;
    }

    //--- DATABASE MAPPING : default_op_hours ( int4 ) 
    /**
     * Set the "defaultOpHours" field value
     * This field is mapped on the database column "default_op_hours" ( type "int4", NotNull : false ) 
     * @param defaultOpHours
     */
    public void setDefaultOpHours( Integer defaultOpHours )
    {
        this.defaultOpHours = defaultOpHours;
    }
    /**
     * Get the "defaultOpHours" field value
     * This field is mapped on the database column "default_op_hours" ( type "int4", NotNull : false ) 
     * @return the field value
     */
    public Integer getDefaultOpHours()
    {
        return this.defaultOpHours;
    }

    //--- DATABASE MAPPING : default_op_hours_uom_code ( int4 ) 
    /**
     * Set the "defaultOpHoursUomCode" field value
     * This field is mapped on the database column "default_op_hours_uom_code" ( type "int4", NotNull : false ) 
     * @param defaultOpHoursUomCode
     */
    public void setDefaultOpHoursUomCode( Integer defaultOpHoursUomCode )
    {
        this.defaultOpHoursUomCode = defaultOpHoursUomCode;
    }
    /**
     * Get the "defaultOpHoursUomCode" field value
     * This field is mapped on the database column "default_op_hours_uom_code" ( type "int4", NotNull : false ) 
     * @return the field value
     */
    public Integer getDefaultOpHoursUomCode()
    {
        return this.defaultOpHoursUomCode;
    }

    //--- DATABASE MAPPING : default_op_cycle_cnt ( int4 ) 
    /**
     * Set the "defaultOpCycleCnt" field value
     * This field is mapped on the database column "default_op_cycle_cnt" ( type "int4", NotNull : false ) 
     * @param defaultOpCycleCnt
     */
    public void setDefaultOpCycleCnt( Integer defaultOpCycleCnt )
    {
        this.defaultOpCycleCnt = defaultOpCycleCnt;
    }
    /**
     * Get the "defaultOpCycleCnt" field value
     * This field is mapped on the database column "default_op_cycle_cnt" ( type "int4", NotNull : false ) 
     * @return the field value
     */
    public Integer getDefaultOpCycleCnt()
    {
        return this.defaultOpCycleCnt;
    }

    //--- DATABASE MAPPING : remote_monitored_ind ( bpchar ) 
    /**
     * Set the "remoteMonitoredInd" field value
     * This field is mapped on the database column "remote_monitored_ind" ( type "bpchar", NotNull : false ) 
     * @param remoteMonitoredInd
     */
    public void setRemoteMonitoredInd( String remoteMonitoredInd )
    {
        this.remoteMonitoredInd = remoteMonitoredInd;
    }
    /**
     * Get the "remoteMonitoredInd" field value
     * This field is mapped on the database column "remote_monitored_ind" ( type "bpchar", NotNull : false ) 
     * @return the field value
     */
    public String getRemoteMonitoredInd()
    {
        return this.remoteMonitoredInd;
    }

    //--- DATABASE MAPPING : last_inprocess_date ( timestamp ) 
    /**
     * Set the "lastInprocessDate" field value
     * This field is mapped on the database column "last_inprocess_date" ( type "timestamp", NotNull : false ) 
     * @param lastInprocessDate
     */
    public void setLastInprocessDate( Date lastInprocessDate )
    {
        this.lastInprocessDate = lastInprocessDate;
    }
    /**
     * Get the "lastInprocessDate" field value
     * This field is mapped on the database column "last_inprocess_date" ( type "timestamp", NotNull : false ) 
     * @return the field value
     */
    public Date getLastInprocessDate()
    {
        return this.lastInprocessDate;
    }

    //--- DATABASE MAPPING : primary_fuel_code ( varchar ) 
    /**
     * Set the "primaryFuelCode" field value
     * This field is mapped on the database column "primary_fuel_code" ( type "varchar", NotNull : false ) 
     * @param primaryFuelCode
     */
    public void setPrimaryFuelCode( String primaryFuelCode )
    {
        this.primaryFuelCode = primaryFuelCode;
    }
    /**
     * Get the "primaryFuelCode" field value
     * This field is mapped on the database column "primary_fuel_code" ( type "varchar", NotNull : false ) 
     * @return the field value
     */
    public String getPrimaryFuelCode()
    {
        return this.primaryFuelCode;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(productId);
        sb.append("|");
        sb.append(productLine);
        sb.append("|");
        sb.append(productSerialNum);
        sb.append("|");
        sb.append(productType);
        sb.append("|");
        sb.append(lockedInd);
        sb.append("|");
        sb.append(createdBy);
        sb.append("|");
        sb.append(createdDate);
        sb.append("|");
        sb.append(lastUpdatedBy);
        sb.append("|");
        sb.append(lastUpdatedDate);
        sb.append("|");
        sb.append(iadPdmGepsId);
        sb.append("|");
        sb.append(csmGepsId);
        sb.append("|");
        sb.append(operatingStatus);
        sb.append("|");
        sb.append(shipDate);
        sb.append("|");
        sb.append(siteDuns);
        sb.append("|");
        sb.append(firstFireDate);
        sb.append("|");
        sb.append(regionCode);
        sb.append("|");
        sb.append(regionalFsmGepsId);
        sb.append("|");
        sb.append(csaInd);
        sb.append("|");
        sb.append(cpmGepsId);
        sb.append("|");
        sb.append(cod);
        sb.append("|");
        sb.append(leasePoolContractInd);
        sb.append("|");
        sb.append(unitNum);
        sb.append("|");
        sb.append(productOwner);
        sb.append("|");
        sb.append(lockedOrderId);
        sb.append("|");
        sb.append(extnlPackageRefNum);
        sb.append("|");
        sb.append(orapParticipantInd);
        sb.append("|");
        sb.append(drivenEquipCode);
        sb.append("|");
        sb.append(defaultOpHours);
        sb.append("|");
        sb.append(defaultOpHoursUomCode);
        sb.append("|");
        sb.append(defaultOpCycleCnt);
        sb.append("|");
        sb.append(remoteMonitoredInd);
        sb.append("|");
        sb.append(lastInprocessDate);
        sb.append("|");
        sb.append(primaryFuelCode);
        return sb.toString(); 
    } 


}
