/*
 * Java bean class for entity table cctt_product_type 
 * Created on 1 Dec 2016 ( Date ISO 2016-12-01 - Time 22:11:06 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package com.ge.pw.ibct.beans;

import java.io.Serializable;

import java.util.Date;

/**
 * Entity bean for table "cctt_product_type"
 * 
 * @author Telosys Tools Generator
 *
 */
public class CcttProductType implements Serializable
{
    private static final long serialVersionUID = 1L;

    private String     productType  ; // Primary Key

    private String     productTypeDesc ;
    private String     createdBy    ;
    private Date       createdDate  ;
    private String     lastUpdatedBy ;
    private Date       lastUpdatedDate ;
    private Integer    bulletinTypeCode ;

    /**
     * Default constructor
     */
    public CcttProductType()
    {
        super();
    }
    
    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR THE PRIMARY KEY 
    //----------------------------------------------------------------------
    /**
     * Set the "productType" field value
     * This field is mapped on the database column "product_type" ( type "varchar", NotNull : true ) 
     * @param productType
     */
	public void setProductType( String productType )
    {
        this.productType = productType ;
    }
    /**
     * Get the "productType" field value
     * This field is mapped on the database column "product_type" ( type "varchar", NotNull : true ) 
     * @return the field value
     */
	public String getProductType()
    {
        return this.productType;
    }

    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR DATA FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : product_type_desc ( varchar ) 
    /**
     * Set the "productTypeDesc" field value
     * This field is mapped on the database column "product_type_desc" ( type "varchar", NotNull : true ) 
     * @param productTypeDesc
     */
    public void setProductTypeDesc( String productTypeDesc )
    {
        this.productTypeDesc = productTypeDesc;
    }
    /**
     * Get the "productTypeDesc" field value
     * This field is mapped on the database column "product_type_desc" ( type "varchar", NotNull : true ) 
     * @return the field value
     */
    public String getProductTypeDesc()
    {
        return this.productTypeDesc;
    }

    //--- DATABASE MAPPING : created_by ( varchar ) 
    /**
     * Set the "createdBy" field value
     * This field is mapped on the database column "created_by" ( type "varchar", NotNull : true ) 
     * @param createdBy
     */
    public void setCreatedBy( String createdBy )
    {
        this.createdBy = createdBy;
    }
    /**
     * Get the "createdBy" field value
     * This field is mapped on the database column "created_by" ( type "varchar", NotNull : true ) 
     * @return the field value
     */
    public String getCreatedBy()
    {
        return this.createdBy;
    }

    //--- DATABASE MAPPING : created_date ( timestamp ) 
    /**
     * Set the "createdDate" field value
     * This field is mapped on the database column "created_date" ( type "timestamp", NotNull : true ) 
     * @param createdDate
     */
    public void setCreatedDate( Date createdDate )
    {
        this.createdDate = createdDate;
    }
    /**
     * Get the "createdDate" field value
     * This field is mapped on the database column "created_date" ( type "timestamp", NotNull : true ) 
     * @return the field value
     */
    public Date getCreatedDate()
    {
        return this.createdDate;
    }

    //--- DATABASE MAPPING : last_updated_by ( varchar ) 
    /**
     * Set the "lastUpdatedBy" field value
     * This field is mapped on the database column "last_updated_by" ( type "varchar", NotNull : true ) 
     * @param lastUpdatedBy
     */
    public void setLastUpdatedBy( String lastUpdatedBy )
    {
        this.lastUpdatedBy = lastUpdatedBy;
    }
    /**
     * Get the "lastUpdatedBy" field value
     * This field is mapped on the database column "last_updated_by" ( type "varchar", NotNull : true ) 
     * @return the field value
     */
    public String getLastUpdatedBy()
    {
        return this.lastUpdatedBy;
    }

    //--- DATABASE MAPPING : last_updated_date ( timestamp ) 
    /**
     * Set the "lastUpdatedDate" field value
     * This field is mapped on the database column "last_updated_date" ( type "timestamp", NotNull : true ) 
     * @param lastUpdatedDate
     */
    public void setLastUpdatedDate( Date lastUpdatedDate )
    {
        this.lastUpdatedDate = lastUpdatedDate;
    }
    /**
     * Get the "lastUpdatedDate" field value
     * This field is mapped on the database column "last_updated_date" ( type "timestamp", NotNull : true ) 
     * @return the field value
     */
    public Date getLastUpdatedDate()
    {
        return this.lastUpdatedDate;
    }

    //--- DATABASE MAPPING : bulletin_type_code ( int4 ) 
    /**
     * Set the "bulletinTypeCode" field value
     * This field is mapped on the database column "bulletin_type_code" ( type "int4", NotNull : false ) 
     * @param bulletinTypeCode
     */
    public void setBulletinTypeCode( Integer bulletinTypeCode )
    {
        this.bulletinTypeCode = bulletinTypeCode;
    }
    /**
     * Get the "bulletinTypeCode" field value
     * This field is mapped on the database column "bulletin_type_code" ( type "int4", NotNull : false ) 
     * @return the field value
     */
    public Integer getBulletinTypeCode()
    {
        return this.bulletinTypeCode;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(productType);
        sb.append("|");
        sb.append(productTypeDesc);
        sb.append("|");
        sb.append(createdBy);
        sb.append("|");
        sb.append(createdDate);
        sb.append("|");
        sb.append(lastUpdatedBy);
        sb.append("|");
        sb.append(lastUpdatedDate);
        sb.append("|");
        sb.append(bulletinTypeCode);
        return sb.toString(); 
    } 


}
