/*
 * Java bean class for entity table cctt_product_line 
 * Created on 1 Dec 2016 ( Date ISO 2016-12-01 - Time 22:11:06 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package com.ge.pw.ibct.beans;

import java.io.Serializable;

import java.util.Date;

/**
 * Entity bean for table "cctt_product_line"
 * 
 * @author Telosys Tools Generator
 *
 */
public class CcttProductLine implements Serializable
{
    private static final long serialVersionUID = 1L;

    private String     productLine  ; // Primary Key

    private String     productLineDesc ;
    private String     createdBy    ;
    private Date       createdDate  ;
    private String     lastUpdatedBy ;
    private Date       lastUpdatedDate ;

    /**
     * Default constructor
     */
    public CcttProductLine()
    {
        super();
    }
    
    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR THE PRIMARY KEY 
    //----------------------------------------------------------------------
    /**
     * Set the "productLine" field value
     * This field is mapped on the database column "product_line" ( type "varchar", NotNull : true ) 
     * @param productLine
     */
	public void setProductLine( String productLine )
    {
        this.productLine = productLine ;
    }
    /**
     * Get the "productLine" field value
     * This field is mapped on the database column "product_line" ( type "varchar", NotNull : true ) 
     * @return the field value
     */
	public String getProductLine()
    {
        return this.productLine;
    }

    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR DATA FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : product_line_desc ( varchar ) 
    /**
     * Set the "productLineDesc" field value
     * This field is mapped on the database column "product_line_desc" ( type "varchar", NotNull : true ) 
     * @param productLineDesc
     */
    public void setProductLineDesc( String productLineDesc )
    {
        this.productLineDesc = productLineDesc;
    }
    /**
     * Get the "productLineDesc" field value
     * This field is mapped on the database column "product_line_desc" ( type "varchar", NotNull : true ) 
     * @return the field value
     */
    public String getProductLineDesc()
    {
        return this.productLineDesc;
    }

    //--- DATABASE MAPPING : created_by ( varchar ) 
    /**
     * Set the "createdBy" field value
     * This field is mapped on the database column "created_by" ( type "varchar", NotNull : true ) 
     * @param createdBy
     */
    public void setCreatedBy( String createdBy )
    {
        this.createdBy = createdBy;
    }
    /**
     * Get the "createdBy" field value
     * This field is mapped on the database column "created_by" ( type "varchar", NotNull : true ) 
     * @return the field value
     */
    public String getCreatedBy()
    {
        return this.createdBy;
    }

    //--- DATABASE MAPPING : created_date ( timestamp ) 
    /**
     * Set the "createdDate" field value
     * This field is mapped on the database column "created_date" ( type "timestamp", NotNull : true ) 
     * @param createdDate
     */
    public void setCreatedDate( Date createdDate )
    {
        this.createdDate = createdDate;
    }
    /**
     * Get the "createdDate" field value
     * This field is mapped on the database column "created_date" ( type "timestamp", NotNull : true ) 
     * @return the field value
     */
    public Date getCreatedDate()
    {
        return this.createdDate;
    }

    //--- DATABASE MAPPING : last_updated_by ( varchar ) 
    /**
     * Set the "lastUpdatedBy" field value
     * This field is mapped on the database column "last_updated_by" ( type "varchar", NotNull : true ) 
     * @param lastUpdatedBy
     */
    public void setLastUpdatedBy( String lastUpdatedBy )
    {
        this.lastUpdatedBy = lastUpdatedBy;
    }
    /**
     * Get the "lastUpdatedBy" field value
     * This field is mapped on the database column "last_updated_by" ( type "varchar", NotNull : true ) 
     * @return the field value
     */
    public String getLastUpdatedBy()
    {
        return this.lastUpdatedBy;
    }

    //--- DATABASE MAPPING : last_updated_date ( timestamp ) 
    /**
     * Set the "lastUpdatedDate" field value
     * This field is mapped on the database column "last_updated_date" ( type "timestamp", NotNull : true ) 
     * @param lastUpdatedDate
     */
    public void setLastUpdatedDate( Date lastUpdatedDate )
    {
        this.lastUpdatedDate = lastUpdatedDate;
    }
    /**
     * Get the "lastUpdatedDate" field value
     * This field is mapped on the database column "last_updated_date" ( type "timestamp", NotNull : true ) 
     * @return the field value
     */
    public Date getLastUpdatedDate()
    {
        return this.lastUpdatedDate;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(productLine);
        sb.append("|");
        sb.append(productLineDesc);
        sb.append("|");
        sb.append(createdBy);
        sb.append("|");
        sb.append(createdDate);
        sb.append("|");
        sb.append(lastUpdatedBy);
        sb.append("|");
        sb.append(lastUpdatedDate);
        return sb.toString(); 
    } 


}
