/*
 * Java bean class for entity table cctt_bulletin_revision 
 * Created on 1 Dec 2016 ( Date ISO 2016-12-01 - Time 22:11:06 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package com.ge.pw.ibct.beans;

import java.io.Serializable;

import java.util.Date;

/**
 * Entity bean for table "cctt_bulletin_revision"
 * 
 * @author Telosys Tools Generator
 *
 */
public class CcttBulletinRevision implements Serializable
{
    private static final long serialVersionUID = 1L;

    private Integer    revId        ; // Primary Key
    private String     bulletinNum  ; // Primary Key
    private Integer    timingCode   ; // Primary Key

    private String     bulletinRevision ;
    private Date       revDate      ;
    private String     remarks      ;
    private String     bulletinDesc ;
    private Integer    categoryCode ;
    private String     complianceLevel ;
    private String     trackImplementationInd ;
    private String     significantInd ;
    private String     createdBy    ;
    private Date       createdDate  ;
    private String     lastUpdatedBy ;
    private Date       lastUpdatedDate ;
    private String     voucherProgramInd ;
    private String     fieldImplMetricInd ;

    /**
     * Default constructor
     */
    public CcttBulletinRevision()
    {
        super();
    }
    
    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR THE PRIMARY KEY 
    //----------------------------------------------------------------------
    /**
     * Set the "revId" field value
     * This field is mapped on the database column "rev_id" ( type "int4", NotNull : true ) 
     * @param revId
     */
	public void setRevId( Integer revId )
    {
        this.revId = revId ;
    }
    /**
     * Get the "revId" field value
     * This field is mapped on the database column "rev_id" ( type "int4", NotNull : true ) 
     * @return the field value
     */
	public Integer getRevId()
    {
        return this.revId;
    }
    /**
     * Set the "bulletinNum" field value
     * This field is mapped on the database column "bulletin_num" ( type "varchar", NotNull : true ) 
     * @param bulletinNum
     */
	public void setBulletinNum( String bulletinNum )
    {
        this.bulletinNum = bulletinNum ;
    }
    /**
     * Get the "bulletinNum" field value
     * This field is mapped on the database column "bulletin_num" ( type "varchar", NotNull : true ) 
     * @return the field value
     */
	public String getBulletinNum()
    {
        return this.bulletinNum;
    }
    /**
     * Set the "timingCode" field value
     * This field is mapped on the database column "timing_code" ( type "int4", NotNull : true ) 
     * @param timingCode
     */
	public void setTimingCode( Integer timingCode )
    {
        this.timingCode = timingCode ;
    }
    /**
     * Get the "timingCode" field value
     * This field is mapped on the database column "timing_code" ( type "int4", NotNull : true ) 
     * @return the field value
     */
	public Integer getTimingCode()
    {
        return this.timingCode;
    }

    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR DATA FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : bulletin_revision ( varchar ) 
    /**
     * Set the "bulletinRevision" field value
     * This field is mapped on the database column "bulletin_revision" ( type "varchar", NotNull : true ) 
     * @param bulletinRevision
     */
    public void setBulletinRevision( String bulletinRevision )
    {
        this.bulletinRevision = bulletinRevision;
    }
    /**
     * Get the "bulletinRevision" field value
     * This field is mapped on the database column "bulletin_revision" ( type "varchar", NotNull : true ) 
     * @return the field value
     */
    public String getBulletinRevision()
    {
        return this.bulletinRevision;
    }

    //--- DATABASE MAPPING : rev_date ( timestamp ) 
    /**
     * Set the "revDate" field value
     * This field is mapped on the database column "rev_date" ( type "timestamp", NotNull : false ) 
     * @param revDate
     */
    public void setRevDate( Date revDate )
    {
        this.revDate = revDate;
    }
    /**
     * Get the "revDate" field value
     * This field is mapped on the database column "rev_date" ( type "timestamp", NotNull : false ) 
     * @return the field value
     */
    public Date getRevDate()
    {
        return this.revDate;
    }

    //--- DATABASE MAPPING : remarks ( varchar ) 
    /**
     * Set the "remarks" field value
     * This field is mapped on the database column "remarks" ( type "varchar", NotNull : false ) 
     * @param remarks
     */
    public void setRemarks( String remarks )
    {
        this.remarks = remarks;
    }
    /**
     * Get the "remarks" field value
     * This field is mapped on the database column "remarks" ( type "varchar", NotNull : false ) 
     * @return the field value
     */
    public String getRemarks()
    {
        return this.remarks;
    }

    //--- DATABASE MAPPING : bulletin_desc ( varchar ) 
    /**
     * Set the "bulletinDesc" field value
     * This field is mapped on the database column "bulletin_desc" ( type "varchar", NotNull : true ) 
     * @param bulletinDesc
     */
    public void setBulletinDesc( String bulletinDesc )
    {
        this.bulletinDesc = bulletinDesc;
    }
    /**
     * Get the "bulletinDesc" field value
     * This field is mapped on the database column "bulletin_desc" ( type "varchar", NotNull : true ) 
     * @return the field value
     */
    public String getBulletinDesc()
    {
        return this.bulletinDesc;
    }

    //--- DATABASE MAPPING : category_code ( int4 ) 
    /**
     * Set the "categoryCode" field value
     * This field is mapped on the database column "category_code" ( type "int4", NotNull : true ) 
     * @param categoryCode
     */
    public void setCategoryCode( Integer categoryCode )
    {
        this.categoryCode = categoryCode;
    }
    /**
     * Get the "categoryCode" field value
     * This field is mapped on the database column "category_code" ( type "int4", NotNull : true ) 
     * @return the field value
     */
    public Integer getCategoryCode()
    {
        return this.categoryCode;
    }

    //--- DATABASE MAPPING : compliance_level ( varchar ) 
    /**
     * Set the "complianceLevel" field value
     * This field is mapped on the database column "compliance_level" ( type "varchar", NotNull : true ) 
     * @param complianceLevel
     */
    public void setComplianceLevel( String complianceLevel )
    {
        this.complianceLevel = complianceLevel;
    }
    /**
     * Get the "complianceLevel" field value
     * This field is mapped on the database column "compliance_level" ( type "varchar", NotNull : true ) 
     * @return the field value
     */
    public String getComplianceLevel()
    {
        return this.complianceLevel;
    }

    //--- DATABASE MAPPING : track_implementation_ind ( bpchar ) 
    /**
     * Set the "trackImplementationInd" field value
     * This field is mapped on the database column "track_implementation_ind" ( type "bpchar", NotNull : true ) 
     * @param trackImplementationInd
     */
    public void setTrackImplementationInd( String trackImplementationInd )
    {
        this.trackImplementationInd = trackImplementationInd;
    }
    /**
     * Get the "trackImplementationInd" field value
     * This field is mapped on the database column "track_implementation_ind" ( type "bpchar", NotNull : true ) 
     * @return the field value
     */
    public String getTrackImplementationInd()
    {
        return this.trackImplementationInd;
    }

    //--- DATABASE MAPPING : significant_ind ( bpchar ) 
    /**
     * Set the "significantInd" field value
     * This field is mapped on the database column "significant_ind" ( type "bpchar", NotNull : false ) 
     * @param significantInd
     */
    public void setSignificantInd( String significantInd )
    {
        this.significantInd = significantInd;
    }
    /**
     * Get the "significantInd" field value
     * This field is mapped on the database column "significant_ind" ( type "bpchar", NotNull : false ) 
     * @return the field value
     */
    public String getSignificantInd()
    {
        return this.significantInd;
    }

    //--- DATABASE MAPPING : created_by ( varchar ) 
    /**
     * Set the "createdBy" field value
     * This field is mapped on the database column "created_by" ( type "varchar", NotNull : true ) 
     * @param createdBy
     */
    public void setCreatedBy( String createdBy )
    {
        this.createdBy = createdBy;
    }
    /**
     * Get the "createdBy" field value
     * This field is mapped on the database column "created_by" ( type "varchar", NotNull : true ) 
     * @return the field value
     */
    public String getCreatedBy()
    {
        return this.createdBy;
    }

    //--- DATABASE MAPPING : created_date ( timestamp ) 
    /**
     * Set the "createdDate" field value
     * This field is mapped on the database column "created_date" ( type "timestamp", NotNull : true ) 
     * @param createdDate
     */
    public void setCreatedDate( Date createdDate )
    {
        this.createdDate = createdDate;
    }
    /**
     * Get the "createdDate" field value
     * This field is mapped on the database column "created_date" ( type "timestamp", NotNull : true ) 
     * @return the field value
     */
    public Date getCreatedDate()
    {
        return this.createdDate;
    }

    //--- DATABASE MAPPING : last_updated_by ( varchar ) 
    /**
     * Set the "lastUpdatedBy" field value
     * This field is mapped on the database column "last_updated_by" ( type "varchar", NotNull : true ) 
     * @param lastUpdatedBy
     */
    public void setLastUpdatedBy( String lastUpdatedBy )
    {
        this.lastUpdatedBy = lastUpdatedBy;
    }
    /**
     * Get the "lastUpdatedBy" field value
     * This field is mapped on the database column "last_updated_by" ( type "varchar", NotNull : true ) 
     * @return the field value
     */
    public String getLastUpdatedBy()
    {
        return this.lastUpdatedBy;
    }

    //--- DATABASE MAPPING : last_updated_date ( timestamp ) 
    /**
     * Set the "lastUpdatedDate" field value
     * This field is mapped on the database column "last_updated_date" ( type "timestamp", NotNull : true ) 
     * @param lastUpdatedDate
     */
    public void setLastUpdatedDate( Date lastUpdatedDate )
    {
        this.lastUpdatedDate = lastUpdatedDate;
    }
    /**
     * Get the "lastUpdatedDate" field value
     * This field is mapped on the database column "last_updated_date" ( type "timestamp", NotNull : true ) 
     * @return the field value
     */
    public Date getLastUpdatedDate()
    {
        return this.lastUpdatedDate;
    }

    //--- DATABASE MAPPING : voucher_program_ind ( bpchar ) 
    /**
     * Set the "voucherProgramInd" field value
     * This field is mapped on the database column "voucher_program_ind" ( type "bpchar", NotNull : false ) 
     * @param voucherProgramInd
     */
    public void setVoucherProgramInd( String voucherProgramInd )
    {
        this.voucherProgramInd = voucherProgramInd;
    }
    /**
     * Get the "voucherProgramInd" field value
     * This field is mapped on the database column "voucher_program_ind" ( type "bpchar", NotNull : false ) 
     * @return the field value
     */
    public String getVoucherProgramInd()
    {
        return this.voucherProgramInd;
    }

    //--- DATABASE MAPPING : field_impl_metric_ind ( bpchar ) 
    /**
     * Set the "fieldImplMetricInd" field value
     * This field is mapped on the database column "field_impl_metric_ind" ( type "bpchar", NotNull : false ) 
     * @param fieldImplMetricInd
     */
    public void setFieldImplMetricInd( String fieldImplMetricInd )
    {
        this.fieldImplMetricInd = fieldImplMetricInd;
    }
    /**
     * Get the "fieldImplMetricInd" field value
     * This field is mapped on the database column "field_impl_metric_ind" ( type "bpchar", NotNull : false ) 
     * @return the field value
     */
    public String getFieldImplMetricInd()
    {
        return this.fieldImplMetricInd;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(revId);
        sb.append("|");
        sb.append(bulletinNum);
        sb.append("|");
        sb.append(bulletinRevision);
        sb.append("|");
        sb.append(revDate);
        sb.append("|");
        sb.append(remarks);
        sb.append("|");
        sb.append(bulletinDesc);
        sb.append("|");
        sb.append(categoryCode);
        sb.append("|");
        sb.append(complianceLevel);
        sb.append("|");
        sb.append(trackImplementationInd);
        sb.append("|");
        sb.append(timingCode);
        sb.append("|");
        sb.append(significantInd);
        sb.append("|");
        sb.append(createdBy);
        sb.append("|");
        sb.append(createdDate);
        sb.append("|");
        sb.append(lastUpdatedBy);
        sb.append("|");
        sb.append(lastUpdatedDate);
        sb.append("|");
        sb.append(voucherProgramInd);
        sb.append("|");
        sb.append(fieldImplMetricInd);
        return sb.toString(); 
    } 


}
