/*
 * Created on 25 Nov 2016 ( Time 21:24:46 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.ge.pw.ibct.entity;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "cctt_product_type"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="cctt_product_type", schema="cct" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="CcttProductTypeEntity.countAll", query="SELECT COUNT(x) FROM CcttProductTypeEntity x" )
} )
public class CcttProductTypeEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="product_type", nullable=false, length=10)
    private String     productType  ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="product_type_desc", nullable=false, length=80)
    private String     productTypeDesc ;

    @Column(name="created_by", nullable=false, length=20)
    private String     createdBy    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_date", nullable=false)
    private Date       createdDate  ;

    @Column(name="last_updated_by", nullable=false, length=20)
    private String     lastUpdatedBy ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="last_updated_date", nullable=false)
    private Date       lastUpdatedDate ;

    @Column(name="bulletin_type_code")
    private Integer    bulletinTypeCode ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public CcttProductTypeEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setProductType( String productType ) {
        this.productType = productType ;
    }
    public String getProductType() {
        return this.productType;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : product_type_desc ( varchar ) 
    public void setProductTypeDesc( String productTypeDesc ) {
        this.productTypeDesc = productTypeDesc;
    }
    public String getProductTypeDesc() {
        return this.productTypeDesc;
    }

    //--- DATABASE MAPPING : created_by ( varchar ) 
    public void setCreatedBy( String createdBy ) {
        this.createdBy = createdBy;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }

    //--- DATABASE MAPPING : created_date ( timestamp ) 
    public void setCreatedDate( Date createdDate ) {
        this.createdDate = createdDate;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }

    //--- DATABASE MAPPING : last_updated_by ( varchar ) 
    public void setLastUpdatedBy( String lastUpdatedBy ) {
        this.lastUpdatedBy = lastUpdatedBy;
    }
    public String getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }

    //--- DATABASE MAPPING : last_updated_date ( timestamp ) 
    public void setLastUpdatedDate( Date lastUpdatedDate ) {
        this.lastUpdatedDate = lastUpdatedDate;
    }
    public Date getLastUpdatedDate() {
        return this.lastUpdatedDate;
    }

    //--- DATABASE MAPPING : bulletin_type_code ( int4 ) 
    public void setBulletinTypeCode( Integer bulletinTypeCode ) {
        this.bulletinTypeCode = bulletinTypeCode;
    }
    public Integer getBulletinTypeCode() {
        return this.bulletinTypeCode;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(productType);
        sb.append("]:"); 
        sb.append(productTypeDesc);
        sb.append("|");
        sb.append(createdBy);
        sb.append("|");
        sb.append(createdDate);
        sb.append("|");
        sb.append(lastUpdatedBy);
        sb.append("|");
        sb.append(lastUpdatedDate);
        sb.append("|");
        sb.append(bulletinTypeCode);
        return sb.toString(); 
    } 

}
