/*
 * Created on 8 Dec 2016 ( Time 20:22:44 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a composite Primary Key  


package com.ge.pw.ibct.entity;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "cctt_bulletin_product"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="cctt_bulletin_product", schema="cct" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="CcttBulletinProductEntity.countAll", query="SELECT COUNT(x) FROM CcttBulletinProductEntity x" )
} )
public class CcttBulletinProductEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( EMBEDDED IN AN EXTERNAL CLASS )  
    //----------------------------------------------------------------------
	@EmbeddedId
    private CcttBulletinProductEntityKey compositePrimaryKey ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="to_serial_num", length=20)
    private String     toSerialNum  ;

    @Column(name="created_by", nullable=false, length=20)
    private String     createdBy    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_date", nullable=false)
    private Date       createdDate  ;

    @Column(name="last_updated_by", nullable=false, length=20)
    private String     lastUpdatedBy ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="last_updated_date", nullable=false)
    private Date       lastUpdatedDate ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="cmpl_end_date")
    private Date       cmplEndDate  ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public CcttBulletinProductEntity() {
		super();
		this.compositePrimaryKey = new CcttBulletinProductEntityKey();       
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE COMPOSITE KEY 
    //----------------------------------------------------------------------
    public void setFromSerialNum( String fromSerialNum ) {
        this.compositePrimaryKey.setFromSerialNum( fromSerialNum ) ;
    }
    public String getFromSerialNum() {
        return this.compositePrimaryKey.getFromSerialNum() ;
    }
    public void setRevId( Integer revId ) {
        this.compositePrimaryKey.setRevId( revId ) ;
    }
    public Integer getRevId() {
        return this.compositePrimaryKey.getRevId() ;
    }
    public void setBulletinNum( String bulletinNum ) {
        this.compositePrimaryKey.setBulletinNum( bulletinNum ) ;
    }
    public String getBulletinNum() {
        return this.compositePrimaryKey.getBulletinNum() ;
    }
    public void setTimingCode( Integer timingCode ) {
        this.compositePrimaryKey.setTimingCode( timingCode ) ;
    }
    public Integer getTimingCode() {
        return this.compositePrimaryKey.getTimingCode() ;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : to_serial_num ( varchar ) 
    public void setToSerialNum( String toSerialNum ) {
        this.toSerialNum = toSerialNum;
    }
    public String getToSerialNum() {
        return this.toSerialNum;
    }

    //--- DATABASE MAPPING : created_by ( varchar ) 
    public void setCreatedBy( String createdBy ) {
        this.createdBy = createdBy;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }

    //--- DATABASE MAPPING : created_date ( timestamp ) 
    public void setCreatedDate( Date createdDate ) {
        this.createdDate = createdDate;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }

    //--- DATABASE MAPPING : last_updated_by ( varchar ) 
    public void setLastUpdatedBy( String lastUpdatedBy ) {
        this.lastUpdatedBy = lastUpdatedBy;
    }
    public String getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }

    //--- DATABASE MAPPING : last_updated_date ( timestamp ) 
    public void setLastUpdatedDate( Date lastUpdatedDate ) {
        this.lastUpdatedDate = lastUpdatedDate;
    }
    public Date getLastUpdatedDate() {
        return this.lastUpdatedDate;
    }

    //--- DATABASE MAPPING : cmpl_end_date ( timestamp ) 
    public void setCmplEndDate( Date cmplEndDate ) {
        this.cmplEndDate = cmplEndDate;
    }
    public Date getCmplEndDate() {
        return this.cmplEndDate;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        if ( compositePrimaryKey != null ) {  
            sb.append(compositePrimaryKey.toString());  
        }  
        else {  
            sb.append( "(null-key)" ); 
        }  
        sb.append("]:"); 
        sb.append(toSerialNum);
        sb.append("|");
        sb.append(createdBy);
        sb.append("|");
        sb.append(createdDate);
        sb.append("|");
        sb.append(lastUpdatedBy);
        sb.append("|");
        sb.append(lastUpdatedDate);
        sb.append("|");
        sb.append(cmplEndDate);
        return sb.toString(); 
    } 

}
