/*
 * Created on 25 Nov 2016 ( Time 21:24:46 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.ge.pw.ibct.entity;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "cctt_bulletin"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="cctt_bulletin", schema="cct" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="CcttBulletinEntity.countAll", query="SELECT COUNT(x) FROM CcttBulletinEntity x" )
} )
public class CcttBulletinEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="bulletin_num", nullable=false, length=50)
    private String     bulletinNum  ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="product_line", nullable=false, length=50)
    private String     productLine  ;

    @Column(name="bulletin_type_code", nullable=false)
    private Integer    bulletinTypeCode ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="issue_date", nullable=false)
    private Date       issueDate    ;

    @Column(name="bulletin_status", nullable=false, length=20)
    private String     bulletinStatus ;

    @Column(name="superceded_bulletin_num", length=50)
    private String     supercededBulletinNum ;

    @Column(name="latest_rev_id")
    private Integer    latestRevId  ;

    @Column(name="created_by", nullable=false, length=20)
    private String     createdBy    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_date", nullable=false)
    private Date       createdDate  ;

    @Column(name="last_updated_by", nullable=false, length=20)
    private String     lastUpdatedBy ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="last_updated_date", nullable=false)
    private Date       lastUpdatedDate ;

	// "productLine" (column "product_line") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    /*@ManyToOne
    @JoinColumn(name="product_line", referencedColumnName="product_line")
    private CcttProductLineEntity ccttProductLine;
*/

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public CcttBulletinEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setBulletinNum( String bulletinNum ) {
        this.bulletinNum = bulletinNum ;
    }
    public String getBulletinNum() {
        return this.bulletinNum;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : bulletin_type_code ( int4 ) 
    public void setBulletinTypeCode( Integer bulletinTypeCode ) {
        this.bulletinTypeCode = bulletinTypeCode;
    }
    public Integer getBulletinTypeCode() {
        return this.bulletinTypeCode;
    }

    //--- DATABASE MAPPING : issue_date ( timestamp ) 
    public void setIssueDate( Date issueDate ) {
        this.issueDate = issueDate;
    }
    public Date getIssueDate() {
        return this.issueDate;
    }

    //--- DATABASE MAPPING : bulletin_status ( varchar ) 
    public void setBulletinStatus( String bulletinStatus ) {
        this.bulletinStatus = bulletinStatus;
    }
    public String getBulletinStatus() {
        return this.bulletinStatus;
    }

    //--- DATABASE MAPPING : superceded_bulletin_num ( varchar ) 
    public void setSupercededBulletinNum( String supercededBulletinNum ) {
        this.supercededBulletinNum = supercededBulletinNum;
    }
    public String getSupercededBulletinNum() {
        return this.supercededBulletinNum;
    }

    //--- DATABASE MAPPING : latest_rev_id ( int4 ) 
    public void setLatestRevId( Integer latestRevId ) {
        this.latestRevId = latestRevId;
    }
    public Integer getLatestRevId() {
        return this.latestRevId;
    }

    //--- DATABASE MAPPING : created_by ( varchar ) 
    public void setCreatedBy( String createdBy ) {
        this.createdBy = createdBy;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }

    //--- DATABASE MAPPING : created_date ( timestamp ) 
    public void setCreatedDate( Date createdDate ) {
        this.createdDate = createdDate;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }

    //--- DATABASE MAPPING : last_updated_by ( varchar ) 
    public void setLastUpdatedBy( String lastUpdatedBy ) {
        this.lastUpdatedBy = lastUpdatedBy;
    }
    public String getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }

    //--- DATABASE MAPPING : last_updated_date ( timestamp ) 
    public void setLastUpdatedDate( Date lastUpdatedDate ) {
        this.lastUpdatedDate = lastUpdatedDate;
    }
    public Date getLastUpdatedDate() {
        return this.lastUpdatedDate;
    }

    public void setProductLine( String productLine ) {
        this.productLine = productLine;
    }
    public String getProductLine() {
        return this.productLine;
    }
    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    /*public void setCcttProductLine( CcttProductLineEntity ccttProductLine ) {
        this.ccttProductLine = ccttProductLine;
    }
    public CcttProductLineEntity getCcttProductLine() {
        return this.ccttProductLine;
    }*/


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(bulletinNum);
        sb.append("]:"); 
        sb.append(bulletinTypeCode);
        sb.append("|");
        sb.append(issueDate);
        sb.append("|");
        sb.append(bulletinStatus);
        sb.append("|");
        sb.append(supercededBulletinNum);
        sb.append("|");
        sb.append(latestRevId);
        sb.append("|");
        sb.append(createdBy);
        sb.append("|");
        sb.append(createdDate);
        sb.append("|");
        sb.append(lastUpdatedBy);
        sb.append("|");
        sb.append(lastUpdatedDate);
        return sb.toString(); 
    } 

}
