/*
 * Created on 25 Nov 2016 ( Time 21:24:46 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.ge.pw.ibct.entity;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;
import java.util.List;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "cctt_product_line"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="cctt_product_line", schema="cct" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="CcttProductLineEntity.countAll", query="SELECT COUNT(x) FROM CcttProductLineEntity x" )
} )
public class CcttProductLineEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="product_line", nullable=false, length=25)
    private String     productLine  ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="product_line_desc", nullable=false, length=80)
    private String     productLineDesc ;

    @Column(name="created_by", nullable=false, length=20)
    private String     createdBy    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_date", nullable=false)
    private Date       createdDate  ;

    @Column(name="last_updated_by", nullable=false, length=20)
    private String     lastUpdatedBy ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="last_updated_date", nullable=false)
    private Date       lastUpdatedDate ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    /*@OneToMany(mappedBy="ccttProductLine", targetEntity=CcttCrProductEntity.class)
    private List<CcttCrProductEntity> listOfCcttCrProduct;

    @OneToMany(mappedBy="ccttProductLine", targetEntity=CcttBulletinEntity.class)
    private List<CcttBulletinEntity> listOfCcttBulletin;
*/

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public CcttProductLineEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setProductLine( String productLine ) {
        this.productLine = productLine ;
    }
    public String getProductLine() {
        return this.productLine;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : product_line_desc ( varchar ) 
    public void setProductLineDesc( String productLineDesc ) {
        this.productLineDesc = productLineDesc;
    }
    public String getProductLineDesc() {
        return this.productLineDesc;
    }

    //--- DATABASE MAPPING : created_by ( varchar ) 
    public void setCreatedBy( String createdBy ) {
        this.createdBy = createdBy;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }

    //--- DATABASE MAPPING : created_date ( timestamp ) 
    public void setCreatedDate( Date createdDate ) {
        this.createdDate = createdDate;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }

    //--- DATABASE MAPPING : last_updated_by ( varchar ) 
    public void setLastUpdatedBy( String lastUpdatedBy ) {
        this.lastUpdatedBy = lastUpdatedBy;
    }
    public String getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }

    //--- DATABASE MAPPING : last_updated_date ( timestamp ) 
    public void setLastUpdatedDate( Date lastUpdatedDate ) {
        this.lastUpdatedDate = lastUpdatedDate;
    }
    public Date getLastUpdatedDate() {
        return this.lastUpdatedDate;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
   /* public void setListOfCcttCrProduct( List<CcttCrProductEntity> listOfCcttCrProduct ) {
        this.listOfCcttCrProduct = listOfCcttCrProduct;
    }
    public List<CcttCrProductEntity> getListOfCcttCrProduct() {
        return this.listOfCcttCrProduct;
    }

    public void setListOfCcttBulletin( List<CcttBulletinEntity> listOfCcttBulletin ) {
        this.listOfCcttBulletin = listOfCcttBulletin;
    }
    public List<CcttBulletinEntity> getListOfCcttBulletin() {
        return this.listOfCcttBulletin;
    }
*/

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(productLine);
        sb.append("]:"); 
        sb.append(productLineDesc);
        sb.append("|");
        sb.append(createdBy);
        sb.append("|");
        sb.append(createdDate);
        sb.append("|");
        sb.append(lastUpdatedBy);
        sb.append("|");
        sb.append(lastUpdatedDate);
        return sb.toString(); 
    } 

}
