/*
 * Created on 25 Nov 2016 ( Time 21:24:46 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a composite Primary Key  


package com.ge.pw.ibct.entity;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "cctt_bulletin_revision"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="cctt_bulletin_revision", schema="cct" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="CcttBulletinRevisionEntity.countAll", query="SELECT COUNT(x) FROM CcttBulletinRevisionEntity x" )
} )
public class CcttBulletinRevisionEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( EMBEDDED IN AN EXTERNAL CLASS )  
    //----------------------------------------------------------------------
	@EmbeddedId
    private CcttBulletinRevisionEntityKey compositePrimaryKey ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="bulletin_revision", nullable=false, length=20)
    private String     bulletinRevision ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="rev_date")
    private Date       revDate      ;

    @Column(name="remarks", length=255)
    private String     remarks      ;

    @Column(name="bulletin_desc", nullable=false, length=200)
    private String     bulletinDesc ;

    @Column(name="category_code", nullable=false)
    private Integer    categoryCode ;

    @Column(name="compliance_level", nullable=false, length=10)
    private String     complianceLevel ;

    @Column(name="track_implementation_ind", nullable=false, length=1)
    private String     trackImplementationInd ;

    @Column(name="significant_ind", length=1)
    private String     significantInd ;

    @Column(name="created_by", nullable=false, length=20)
    private String     createdBy    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_date", nullable=false)
    private Date       createdDate  ;

    @Column(name="last_updated_by", nullable=false, length=20)
    private String     lastUpdatedBy ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="last_updated_date", nullable=false)
    private Date       lastUpdatedDate ;

    @Column(name="voucher_program_ind", length=1)
    private String     voucherProgramInd ;

    @Column(name="field_impl_metric_ind", length=1)
    private String     fieldImplMetricInd ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public CcttBulletinRevisionEntity() {
		super();
		this.compositePrimaryKey = new CcttBulletinRevisionEntityKey();       
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE COMPOSITE KEY 
    //----------------------------------------------------------------------
    public void setRevId( Integer revId ) {
        this.compositePrimaryKey.setRevId( revId ) ;
    }
    public Integer getRevId() {
        return this.compositePrimaryKey.getRevId() ;
    }
    public void setBulletinNum( String bulletinNum ) {
        this.compositePrimaryKey.setBulletinNum( bulletinNum ) ;
    }
    public String getBulletinNum() {
        return this.compositePrimaryKey.getBulletinNum() ;
    }
    public void setTimingCode( Integer timingCode ) {
        this.compositePrimaryKey.setTimingCode( timingCode ) ;
    }
    public Integer getTimingCode() {
        return this.compositePrimaryKey.getTimingCode() ;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : bulletin_revision ( varchar ) 
    public void setBulletinRevision( String bulletinRevision ) {
        this.bulletinRevision = bulletinRevision;
    }
    public String getBulletinRevision() {
        return this.bulletinRevision;
    }

    //--- DATABASE MAPPING : rev_date ( timestamp ) 
    public void setRevDate( Date revDate ) {
        this.revDate = revDate;
    }
    public Date getRevDate() {
        return this.revDate;
    }

    //--- DATABASE MAPPING : remarks ( varchar ) 
    public void setRemarks( String remarks ) {
        this.remarks = remarks;
    }
    public String getRemarks() {
        return this.remarks;
    }

    //--- DATABASE MAPPING : bulletin_desc ( varchar ) 
    public void setBulletinDesc( String bulletinDesc ) {
        this.bulletinDesc = bulletinDesc;
    }
    public String getBulletinDesc() {
        return this.bulletinDesc;
    }

    //--- DATABASE MAPPING : category_code ( int4 ) 
    public void setCategoryCode( Integer categoryCode ) {
        this.categoryCode = categoryCode;
    }
    public Integer getCategoryCode() {
        return this.categoryCode;
    }

    //--- DATABASE MAPPING : compliance_level ( varchar ) 
    public void setComplianceLevel( String complianceLevel ) {
        this.complianceLevel = complianceLevel;
    }
    public String getComplianceLevel() {
        return this.complianceLevel;
    }

    //--- DATABASE MAPPING : track_implementation_ind ( bpchar ) 
    public void setTrackImplementationInd( String trackImplementationInd ) {
        this.trackImplementationInd = trackImplementationInd;
    }
    public String getTrackImplementationInd() {
        return this.trackImplementationInd;
    }

    //--- DATABASE MAPPING : significant_ind ( bpchar ) 
    public void setSignificantInd( String significantInd ) {
        this.significantInd = significantInd;
    }
    public String getSignificantInd() {
        return this.significantInd;
    }

    //--- DATABASE MAPPING : created_by ( varchar ) 
    public void setCreatedBy( String createdBy ) {
        this.createdBy = createdBy;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }

    //--- DATABASE MAPPING : created_date ( timestamp ) 
    public void setCreatedDate( Date createdDate ) {
        this.createdDate = createdDate;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }

    //--- DATABASE MAPPING : last_updated_by ( varchar ) 
    public void setLastUpdatedBy( String lastUpdatedBy ) {
        this.lastUpdatedBy = lastUpdatedBy;
    }
    public String getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }

    //--- DATABASE MAPPING : last_updated_date ( timestamp ) 
    public void setLastUpdatedDate( Date lastUpdatedDate ) {
        this.lastUpdatedDate = lastUpdatedDate;
    }
    public Date getLastUpdatedDate() {
        return this.lastUpdatedDate;
    }

    //--- DATABASE MAPPING : voucher_program_ind ( bpchar ) 
    public void setVoucherProgramInd( String voucherProgramInd ) {
        this.voucherProgramInd = voucherProgramInd;
    }
    public String getVoucherProgramInd() {
        return this.voucherProgramInd;
    }

    //--- DATABASE MAPPING : field_impl_metric_ind ( bpchar ) 
    public void setFieldImplMetricInd( String fieldImplMetricInd ) {
        this.fieldImplMetricInd = fieldImplMetricInd;
    }
    public String getFieldImplMetricInd() {
        return this.fieldImplMetricInd;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        if ( compositePrimaryKey != null ) {  
            sb.append(compositePrimaryKey.toString());  
        }  
        else {  
            sb.append( "(null-key)" ); 
        }  
        sb.append("]:"); 
        sb.append(bulletinRevision);
        sb.append("|");
        sb.append(revDate);
        sb.append("|");
        sb.append(remarks);
        sb.append("|");
        sb.append(bulletinDesc);
        sb.append("|");
        sb.append(categoryCode);
        sb.append("|");
        sb.append(complianceLevel);
        sb.append("|");
        sb.append(trackImplementationInd);
        sb.append("|");
        sb.append(significantInd);
        sb.append("|");
        sb.append(createdBy);
        sb.append("|");
        sb.append(createdDate);
        sb.append("|");
        sb.append(lastUpdatedBy);
        sb.append("|");
        sb.append(lastUpdatedDate);
        sb.append("|");
        sb.append(voucherProgramInd);
        sb.append("|");
        sb.append(fieldImplMetricInd);
        return sb.toString(); 
    } 

}
