/*
 * Created on 12 Dec 2016 ( Time 16:38:51 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.ge.pw.ibct.entity;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "comt_application_code"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="comt_application_code", schema="cct" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="ComtApplicationCodeEntity.countAll", query="SELECT COUNT(x) FROM ComtApplicationCodeEntity x" )
} )
public class ComtApplicationCodeEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="code_id", nullable=false)
    private Long       codeId       ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="application_id", nullable=false, length=30)
    private String     applicationId ;

    @Column(name="code_type", nullable=false, length=30)
    private String     codeType     ;

    @Column(name="code_name", nullable=false, length=50)
    private String     codeName     ;

    @Column(name="code_description", length=200)
    private String     codeDescription ;

    @Column(name="code_value")
    private BigDecimal codeValue    ;

    @Column(name="code_flag", length=1)
    private String     codeFlag     ;

    @Column(name="created_by", length=10)
    private String     createdBy    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_date")
    private Date       createdDate  ;

    @Column(name="last_mod_by", length=20)
    private String     lastModBy    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="last_mod_date")
    private Date       lastModDate  ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public ComtApplicationCodeEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setCodeId( Long codeId ) {
        this.codeId = codeId ;
    }
    public Long getCodeId() {
        return this.codeId;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : application_id ( varchar ) 
    public void setApplicationId( String applicationId ) {
        this.applicationId = applicationId;
    }
    public String getApplicationId() {
        return this.applicationId;
    }

    //--- DATABASE MAPPING : code_type ( varchar ) 
    public void setCodeType( String codeType ) {
        this.codeType = codeType;
    }
    public String getCodeType() {
        return this.codeType;
    }

    //--- DATABASE MAPPING : code_name ( varchar ) 
    public void setCodeName( String codeName ) {
        this.codeName = codeName;
    }
    public String getCodeName() {
        return this.codeName;
    }

    //--- DATABASE MAPPING : code_description ( varchar ) 
    public void setCodeDescription( String codeDescription ) {
        this.codeDescription = codeDescription;
    }
    public String getCodeDescription() {
        return this.codeDescription;
    }

    //--- DATABASE MAPPING : code_value ( numeric ) 
    public void setCodeValue( BigDecimal codeValue ) {
        this.codeValue = codeValue;
    }
    public BigDecimal getCodeValue() {
        return this.codeValue;
    }

    //--- DATABASE MAPPING : code_flag ( bpchar ) 
    public void setCodeFlag( String codeFlag ) {
        this.codeFlag = codeFlag;
    }
    public String getCodeFlag() {
        return this.codeFlag;
    }

    //--- DATABASE MAPPING : created_by ( varchar ) 
    public void setCreatedBy( String createdBy ) {
        this.createdBy = createdBy;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }

    //--- DATABASE MAPPING : created_date ( timestamp ) 
    public void setCreatedDate( Date createdDate ) {
        this.createdDate = createdDate;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }

    //--- DATABASE MAPPING : last_mod_by ( varchar ) 
    public void setLastModBy( String lastModBy ) {
        this.lastModBy = lastModBy;
    }
    public String getLastModBy() {
        return this.lastModBy;
    }

    //--- DATABASE MAPPING : last_mod_date ( timestamp ) 
    public void setLastModDate( Date lastModDate ) {
        this.lastModDate = lastModDate;
    }
    public Date getLastModDate() {
        return this.lastModDate;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(codeId);
        sb.append("]:"); 
        sb.append(applicationId);
        sb.append("|");
        sb.append(codeType);
        sb.append("|");
        sb.append(codeName);
        sb.append("|");
        sb.append(codeDescription);
        sb.append("|");
        sb.append(codeValue);
        sb.append("|");
        sb.append(codeFlag);
        sb.append("|");
        sb.append(createdBy);
        sb.append("|");
        sb.append(createdDate);
        sb.append("|");
        sb.append(lastModBy);
        sb.append("|");
        sb.append(lastModDate);
        return sb.toString(); 
    } 

}
